// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: grpc-server/proto/fileservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagem vazia para requisições sem parâmetros
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_fileservice_proto_rawDescGZIP(), []int{0}
}

// Resposta com lista de arquivos
type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_fileservice_proto_rawDescGZIP(), []int{1}
}

func (x *FileListResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

// Requisição para upload de arquivo
type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_fileservice_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Resultado de uma operação
type OperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_fileservice_proto_rawDescGZIP(), []int{3}
}

func (x *OperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Requisição para download de arquivo
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_fileservice_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Resposta com dados do arquivo
type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_proto_fileservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_server_proto_fileservice_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpc_server_proto_fileservice_proto protoreflect.FileDescriptor

const file_grpc_server_proto_fileservice_proto_rawDesc = "" +
	"\n" +
	"#grpc-server/proto/fileservice.proto\x12\vfileservice\"\a\n" +
	"\x05Empty\"(\n" +
	"\x10FileListResponse\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\"7\n" +
	"\rUploadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"E\n" +
	"\x0fOperationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x10DownloadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xe2\x01\n" +
	"\vFileService\x12>\n" +
	"\tListFiles\x12\x12.fileservice.Empty\x1a\x1d.fileservice.FileListResponse\x12F\n" +
	"\n" +
	"UploadFile\x12\x1a.fileservice.UploadRequest\x1a\x1c.fileservice.OperationResult\x12K\n" +
	"\fDownloadFile\x12\x1c.fileservice.DownloadRequest\x1a\x1d.fileservice.DownloadResponseB+Z)grpc-rabbitmq-fileshare/grpc-server/protob\x06proto3"

var (
	file_grpc_server_proto_fileservice_proto_rawDescOnce sync.Once
	file_grpc_server_proto_fileservice_proto_rawDescData []byte
)

func file_grpc_server_proto_fileservice_proto_rawDescGZIP() []byte {
	file_grpc_server_proto_fileservice_proto_rawDescOnce.Do(func() {
		file_grpc_server_proto_fileservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_server_proto_fileservice_proto_rawDesc), len(file_grpc_server_proto_fileservice_proto_rawDesc)))
	})
	return file_grpc_server_proto_fileservice_proto_rawDescData
}

var file_grpc_server_proto_fileservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_server_proto_fileservice_proto_goTypes = []any{
	(*Empty)(nil),            // 0: fileservice.Empty
	(*FileListResponse)(nil), // 1: fileservice.FileListResponse
	(*UploadRequest)(nil),    // 2: fileservice.UploadRequest
	(*OperationResult)(nil),  // 3: fileservice.OperationResult
	(*DownloadRequest)(nil),  // 4: fileservice.DownloadRequest
	(*DownloadResponse)(nil), // 5: fileservice.DownloadResponse
}
var file_grpc_server_proto_fileservice_proto_depIdxs = []int32{
	0, // 0: fileservice.FileService.ListFiles:input_type -> fileservice.Empty
	2, // 1: fileservice.FileService.UploadFile:input_type -> fileservice.UploadRequest
	4, // 2: fileservice.FileService.DownloadFile:input_type -> fileservice.DownloadRequest
	1, // 3: fileservice.FileService.ListFiles:output_type -> fileservice.FileListResponse
	3, // 4: fileservice.FileService.UploadFile:output_type -> fileservice.OperationResult
	5, // 5: fileservice.FileService.DownloadFile:output_type -> fileservice.DownloadResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_server_proto_fileservice_proto_init() }
func file_grpc_server_proto_fileservice_proto_init() {
	if File_grpc_server_proto_fileservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_server_proto_fileservice_proto_rawDesc), len(file_grpc_server_proto_fileservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_server_proto_fileservice_proto_goTypes,
		DependencyIndexes: file_grpc_server_proto_fileservice_proto_depIdxs,
		MessageInfos:      file_grpc_server_proto_fileservice_proto_msgTypes,
	}.Build()
	File_grpc_server_proto_fileservice_proto = out.File
	file_grpc_server_proto_fileservice_proto_goTypes = nil
	file_grpc_server_proto_fileservice_proto_depIdxs = nil
}
