FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copia os arquivos de dependências
COPY go.mod go.sum ./
RUN go mod download

# Copia o código fonte
COPY . .

# Compila o servidor RabbitMQ
WORKDIR /app/rabbit-server
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/rabbit-server .

# Imagem final
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/rabbit-server .

CMD ["./rabbit-server"]

